import Hero from "@/components/contacts/Hero";
import Map from "@/components/contacts/Map";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Offcanvas from "@/components/header/Offcanvas";

import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>Best NIOS Coaching in India | Contact Us </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="home-page-area">
           <Header/>
           <Offcanvas/>
           <Hero/>
           <Map/>

      

           <Footer/>
      </section>
    </>
  );
}
