import Hero from "@/components/contacts/Hero";
import Map from "@/components/contacts/Map";
import Footer from "@/components/footer/Footer";
import Gallery from "@/components/Gallery";
import Header from "@/components/header/Header";
import Offcanvas from "@/components/header/Offcanvas";
import FAQ from "@/components/home/FAQ";

import Head from "next/head";

export default function Galleryy() {
  return (
    <div className="gallery-area">
      <Head>
        <title>Best NIOS Coaching in India | Gallery </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="home-page-area">
        <Header />
        <Offcanvas />

        <section className="qustion-paper-hero-section tma-hero ">
          <div className="container">
            <div className="hero-text">
              <h1 className="qustion-paper-hero-title mb-4">
                 Photo Gallery
              </h1>
             
            </div>

            <section className="gallery-section-area">
                <Gallery/>
            </section>
               <a href="tel:9839065533" className="cta-button-gallery cta-button1">
                  S.S. Coaching, IIIrd Floor, Shree Chamber, Naza Computer Market, Near Basant Cinema, Hazratganj, Lucknow. Mob No-9839065533
                </a>
          </div>
        </section>

        <FAQ/>


       <div className="container">
         <a href="tel: +91 9935035316" className="cta-button ">
                 For any help related to admission in NIOS please contact SS Coaching on our Mobile No. +91 9935035316
                </a>
       </div>

        <Footer />
      </section>
    </div>
  );
}
