import Hero from "@/components/contacts/Hero";
import Map from "@/components/contacts/Map";
import Footer from "@/components/footer/Footer";
import Gallery from "@/components/Gallery";
import Header from "@/components/header/Header";
import Offcanvas from "@/components/header/Offcanvas";

import Head from "next/head";

export default function Galleryy() {
  return (
    <>
      <Head>
        <title>Best NIOS Coaching in India | Gallery </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="home-page-area">
        <Header />
        <Offcanvas />

        <section className="qustion-paper-hero-section tma-hero">
          <div className="container">
            <div className="hero-text">
              <h1 className="qustion-paper-hero-title">
                 Photo Gallery
              </h1>
             
            </div>

            <section className="gallery-section-area">5
                <Gallery/>
            </section>
          </div>
        </section>

        <Footer />
      </section>
    </>
  );
}
