import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Offcanvas from "@/components/header/Offcanvas";
import Achievements from "@/components/home/Achievements";
import BeastFeatures from "@/components/home/BeastFeatures";
import ChipSection from "@/components/home/ChipSection";
import CoachingStream from "@/components/home/CoachingStream";
import CTA from "@/components/home/CTA";
import CTA2 from "@/components/home/CTA2";
import CTAA, { CTA1 } from "@/components/home/CTA2";
import CTA3 from "@/components/home/CTA3";
import FAQ from "@/components/home/FAQ";
import GoogleReview from "@/components/home/GoogleReview";
import Hero from "@/components/home/Hero";
import HeroMobile from "@/components/home/HeroMobile";
import LearnersNios from "@/components/home/LearnersNios";
import LearnersNiosMobile from "@/components/home/LearnersNiosMobile";
import News from "@/components/home/News";
import NewsMobile from "@/components/home/NewsMobile";
import NIOSInfo from "@/components/home/NIOSInfo";
import QueryForm from "@/components/home/QueryForm";
import QuickLinks from "@/components/home/QuickLinks";
import RecongnitionMobile from "@/components/home/RecognitionMobile";
import Recongnition from "@/components/home/Recongnition";
import StatsSection from "@/components/home/StatsSection";
import StatsSectionMobile from "@/components/home/StatsSectionMobile";
import StepProcess from "@/components/home/StepProcess";
import StepProcessMobile from "@/components/home/StepsProcessMobile";
import StudentSuccess from "@/components/home/StudentSuccess";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Best NIOS Coaching in India | NIOS Admission for Failed Students &amp;
          Dropouts in India
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="home-page-area">
        <Header />
        <Offcanvas />
        {/* <NewsMobile/> */}
        <Hero />
        <HeroMobile />
        <ChipSection />
        <StudentSuccess />
        <StatsSection />
        <StatsSectionMobile />

        <NewsMobile />

        <StepProcessMobile />

        <QueryForm />
        <News />

        <RecongnitionMobile />

        <LearnersNiosMobile />

        <GoogleReview />
        <StepProcess />
        <LearnersNios />
        <div className="container">
          <CTA />
        </div>
        <CoachingStream />

        <Recongnition />
        <Achievements />
        <div className="container">
          <CTA2 />
        </div>

        <NIOSInfo />

        <BeastFeatures />

        <div className="container">
          <CTA3 />
        </div>

        <QuickLinks />
        <FAQ />

        <Footer />
      </section>
    </>
  );
}
