import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Achievements from "@/components/home/Achievements";
import BeastFeatures from "@/components/home/BeastFeatures";
import ChipSection from "@/components/home/ChipSection";
import CoachingStream from "@/components/home/CoachingStream";
import CTA from "@/components/home/CTA";
import CTA2 from "@/components/home/CTA2";
import CTAA, { CTA1 } from "@/components/home/CTA2";
import CTA3 from "@/components/home/CTA3";
import FAQ from "@/components/home/FAQ";
import GoogleReview from "@/components/home/GoogleReview";
import Hero from "@/components/home/Hero";
import LearnersNios from "@/components/home/LearnersNios";
import News from "@/components/home/News";
import NIOSInfo from "@/components/home/NIOSInfo";
import QuickLinks from "@/components/home/QuickLinks";
import Recongnition from "@/components/home/Recongnition";
import StatsSection from "@/components/home/StatsSection";
import StepProcess from "@/components/home/StepProcess";
import StudentSuccess from "@/components/home/StudentSuccess";
import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>Best NIOS Coaching in India | NIOS Admission for Failed Students &amp; Dropouts in India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="home-page-area">
           <Header/>
           <Hero/>
           <ChipSection/>
           <StudentSuccess/>
           <StatsSection/>
           <News/>
           <GoogleReview/>
           <StepProcess/>
           <LearnersNios/>
           <div className="container">
             <CTA/>
           </div>
           <CoachingStream/>
           <Recongnition/>
           <Achievements/>
            <div className="container">
             <CTA2 />
           </div>

           <NIOSInfo/>

           <BeastFeatures/>

            <div className="container">
              <CTA3/>
           </div>

           <QuickLinks/>
           <FAQ/>

           <Footer/>
      </section>
    </>
  );
}
